influxdb:
  image: tutum/influxdb:latest
  ports:
    - '8083:8083'
    - '8086:8086'
  environment:
    - ADMIN_USER="root"
    - INFLUXDB_INIT_PWD="somepassword"
    - PRE_CREATE_DB="tse"
  volumes:
   - /var/influxdb:/data


redis:
  image: redis
  ports:
    - '6379:6379'

elastic:
  image: elasticsearch:2.3.2
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /mnt/elastic:/data




mysql:
  image: mysql:5.7.9
  mem_limit: 1024m
  memswap_limit: 2048m
  environment:
   - MYSQL_DATABASE=bot
   - MYSQL_ROOT_PASSWORD=my-secret-pw
   - MYSQL_USER=bot
   - MYSQL_PASSWORD=bot@123
  volumes:
   - /mnt/db/mysql:/var/lib/mysql
  expose:
   - "3306"
  ports:
   - "3306:3306"


phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - "mysql:db"
  expose:
   - "80"
  ports:
   - "8070:80"

trader:
  build: .
  expose:
   - "80"
  ports:
   - "10823:80"
  links:
   - "mongo-trader:mongo"

mongo-trader:
  image: mongo:3.1.9
  volumes:
   - /mnt/mongo-trader:/data/db